# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://example.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
repository: garrett/jekyll-basic

lang: en

# Build settings
markdown: kramdown
theme: minima

# YAML defaults for pages
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

# GitHub builds with safe mode, so enable it for previewing locally too
safe: true

excerpt_separator: READMORE

# Don't compile these files/dirs into the website
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin

include:
  - _stylesheets
  - _javascript
  - assets/site.js
  - assets/vendor/jquery/dist/
  - assets/vendor/jquery.easing/js/
  - assets/vendor/bootstrap-sass/assets/javascripts/

sass:
  sass_dir: assets/
  style: :compressed

# Let the following Jekyll plugins work in safemode
# (mimicing GitHub's config)
whitelist:
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-github-metadata
    
