# Entries here are displayed under their respective maintainer field.
# If let unset it will be seen as third-party.
# Available options are seen in maintainers.yml and for example be
# - cockpit
# - redhat
# - suse

# The Cockpit group is special, it inherits source, issues, license for the `source: cockpit` entries
cockpit:
  source: https://github.com/cockpit-project/cockpit/
  issues: https://github.com/cockpit-project/cockpit/issues
  license: LGPL 2.1
  comment: |
    This is the default template that "source: cockpit" pulls from, so source, issues, and license don't need to be filled out everywhere.

storaged:
  title: Storage
  package: cockpit-storaged
  source: cockpit
  maintainer: cockpit
  description: |
    Manage your system's storage. Supports local partitions, encryption, NFS, RAID, iSCSI, and more.

networkmanager:
  title: Network
  package: cockpit-networkmanager
  source: cockpit
  maintainer: cockpit
  description: |
    Manage your network interfaces and edit your firewall with ease.

packagekit:
  title: Software Updates (PackageKit)
  package: cockpit-packagekit
  source: cockpit
  maintainer: cockpit
  description: |
    See and apply updates to your system. Supports RPM and DEB based systems through PackageKit.

ostree:
  title: Software Updates (OSTree)
  package: cockpit-ostree
  maintainer: cockpit
  source: https://github.com/cockpit-project/cockpit-ostree
  issues: https://github.com/cockpit-project/cockpit-ostree/issues
  license: LGPL 2.1
  description: |
    Upgrade OSTree-based systems.

machines:
  title: Virtual Machines
  package: cockpit-machines
  source: https://github.com/cockpit-project/cockpit-machines
  issues: https://github.com/cockpit-project/cockpit-machines/issues
  license: LGPL 2.1
  maintainer: cockpit
  description: |
    Create, run, and manage virtual machines.

podman:
  title: Podman Containers
  package: cockpit-podman
  source: https://github.com/cockpit-project/cockpit-podman
  issues: https://github.com/cockpit-project/cockpit-podman/issues
  license: LGPL 2.1
  maintainer: cockpit
  description: |
    Download, use, and manage containers. (Podman replaces Docker.)

selinux:
  title: SELinux
  package: cockpit-selinux
  source: cockpit
  maintainer: cockpit
  description: |
    View and manage SELinux exceptions. Instantly apply overrides and export your rules to apply to other systems.

kdump:
  title: Kernel Dump
  package: cockpit-kdump
  source: cockpit
  maintainer: cockpit
  description: |
    Debugging the Linux kernel? This `kdump` add-on helps with catching stack traces.

image-builder:
  title: Cockpit Image Builder
  package: cockpit-image-builder
  source: https://github.com/osbuild/image-builder-frontend
  issues: https://github.com/osbuild/image-builder-frontend/issues
  maintainer: redhat
  description: |
    On-premise frontend for image building. It allows users to create, manage, and compose custom operating system images, with images stored locally.

sosreport:
  title: Diagnostic Reports
  package: cockpit-sosreport
  source: cockpit
  maintainer: cockpit
  description: |
    Collect system configuration and diagnostic information from systems, to help with diagnosing problems.

files:
  title: Cockpit Files
  package: cockpit-files
  source: https://github.com/cockpit-project/cockpit-files
  issues: https://github.com/cockpit-project/cockpit-files/issues
  maintainer: cockpit
  description: |
    A featureful file browser.

389-ds:
  title: 389 Directory Server
  package: cockpit-389-ds
  homepage: https://directory.fedoraproject.org/docs/389ds/download.html
  source:
  maintainer: redhat
  description: |
    A web-based interface to the enterprise-class Open Source LDAP server for Linux.

session-recording:
  title: Session Recording
  package: cockpit-session-recording
  source: https://github.com/Scribery/cockpit-session-recording
  issues: https://github.com/Scribery/cockpit-session-recording/issues
  maintainer: redhat
  description: |
    Session recording configuration and playback based on [Scribery](https://scribery.github.io/), to record a user's actions for watching later.

subscriptions:
  title: Subscription Manager
  package: subscription-manager-cockpit
  source: https://github.com/candlepin/subscription-manager-cockpit
  issues:
  maintainer: redhat
  description: |
    Manage subscriptions to Red Hat Enterprise Linux.

ha-cluster:
  title: High Availability Cluster Management
  package: cockpit-ha-cluster
  source: https://github.com/ClusterLabs/pcs-web-ui
  maintainer: redhat
  description: |
    Manage Pacemaker based clusters with [PCS](https://github.com/ClusterLabs/pcs).

# leapp:
#   package: cockpit-leap
#   title: Leapp
#   homepage: https://leapp.readthedocs.io/en/latest/
#   source: https://github.com/oamg/leapp
#   license: Apache 2
#   issues: https://github.com/oamg/leapp/issues
#   description: |
#     Leapp is an OS and application modernization framework. It is used to upgrade Red Hat Enterprise Linux. (For example: Upgrading RHEL 7 to 8.)

zfs:
  title: ZFS Manager
  package: cockpit-zfs
  source: https://github.com/45Drives/cockpit-zfs-manager
  issues: https://github.com/45Drives/cockpit-zfs-manager/issues
  prerelease: false
  description: |
    Interactive ZFS on Linux administration.

file-sharing:
  title: File Sharing
  source: https://github.com/45Drives/cockpit-file-sharing
  issues: https://github.com/45Drives/cockpit-file-sharing/issues
  prerelease: false
  description: |
    Easily manage Samba and NFS file sharing.

navigator:
  title: Navigator
  source: https://github.com/45Drives/cockpit-navigator
  issues: https://github.com/45Drives/cockpit-navigator/issues
  prerelease: false
  description: |
    A featureful file browser.

benchmark:
  title: Benchmark
  source: https://github.com/45Drives/cockpit-benchmark
  issues: https://github.com/45Drives/cockpit-benchmark/issues
  prerelease: false
  description: |
    A storage benchmark utility.

tukit:
  title: Software Updates (transactional-update from OpenSUSE with tukit)
  package: cockpit-tukit
  maintainer: suse
  source: https://github.com/openSUSE/cockpit-tukit
  issues: https://github.com/openSUSE/cockpit-tukit/issues
  license: LGPL 2.1
  description: |
    Upgrade systems based on transactional-update from OpenSUSE with tukit.

sensors:
  title: Sensors
  package: cockpit-sensors
  source: https://github.com/ocristopfer/cockpit-sensors
  issues: https://github.com/ocristopfer/cockpit-sensors/issues
  license: LGPL 2.1
  description: |
    List all available sensors on the machine provided by `lm-sensors`.

tailscale:
  title: Tailscale
  package: cockpit-tailscale
  prerelease: true
  source: https://github.com/spotsnel/cockpit-tailscale
  issues: https://github.com/spotsnel/cockpit-tailscale/issues
  license: LGPL 2.1
  description: |
    Manage Tailscale.

headscale:
  title: Headscale
  package: cockpit-headscale
  prerelease: true
  source: https://github.com/spotsnel/cockpit-headscale
  issues: https://github.com/spotsnel/cockpit-headscale/issues
  license: LGPL 2.1
  description: |
    Manage Headscale coordination server.

cloudflared:
  title: Cloudflare tunnels
  package: cockpit-cloudflared
  prerelease: true
  source: https://github.com/spotsnel/cockpit-cloudflared
  issues: https://github.com/spotsnel/cockpit-cloudflared/issues
  license: LGPL 2.1
  description: |
    Show Cloudflare tunnel state.

repos:
  title: Manage Repositories
  package: cockpit-repos
  maintainer: suse
  source: https://github.com/openSUSE/cockpit-repos
  issues: https://github.com/openSUSE/cockpit-repos/issues
  license: LGPL 2.1
  description: |
    Manage package manager repositories on SUSE/openSUSE systems

subscriptions-suse:
  title: Subscription Manager
  package: cockpit-subscriptions
  maintainer: suse
  source: https://github.com/openSUSE/cockpit-subscriptions
  issues: https://github.com/openSUSE/cockpit-subscriptions/issues
  license: LGPL 2.1
  description: |
    Manage your SUSE Linux Enterprise subscriptions.

packages:
  title: Packages
  package: cockpit-packages
  maintainer: suse
  source: https://github.com/openSUSE/cockpit-packages
  issues: https://github.com/openSUSE/cockpit-packages/issues
  license: LGPL 2.1
  description: |
    Install/Uninstall packages.

bootloader:
  title: Bootloader
  prerelease: true
  package: cockpit-bootloader
  maintainer: suse
  source: https://github.com/openSUSE/cockpit-bootloader
  issues: https://github.com/openSUSE/cockpit-bootloader/issues
  license: LGPL 2.1
  description: |
    Manage bootloader configurations.

dockermanager:
  title: Docker Manager
  prerelease: true
  source: https://github.com/chrisjbawden/cockpit-dockermanager
  issues: https://github.com/chrisjbawden/cockpit-dockermanager/issues
  description: |
    A lightweight interface for simple management of docker containers.

backblaze-b2:
  title: Backblaze B2 backup
  prerelease: false
  source: https://github.com/rabol/backblaze-b2
  issues: https://github.com/rabol/backblaze-b2/issues
  description: |
    A lightweight interface for simple back up to Backblaze B2.

ros2-diagnostics:
  title: ROS 2 Diagnostics
  package: cockpit-ros2-diagnostics
  source: https://github.com/clearpathrobotics/cockpit-ros2-diagnostics
  issues: https://github.com/clearpathrobotics/cockpit-ros2-diagnostics/issues
  license: LGPL 2.1
  description: |
    View ROS 2 diagnostics.

package-manager:
  title: Package Manager
  source: https://github.com/hatlabs/cockpit-package-manager
  issues: https://github.com/hatlabs/cockpit-package-manager/issues
  license: LGPL 2.1
  description: |
    DEB (APT) / RPM browsing and installation tool using PackageKit.

port-forward:
  title: Port Forward Manager
  source: https://github.com/kuznetz/cockpit-port-forward
  issues: https://github.com/kuznetz/cockpit-port-forward/issues
  license: MIT
  description: |
    Manage firewalld port forwarding rules and masquerading.

sudo-manager:
  title: Sudo Manager
  source: https://github.com/josephoaks/Cockpit-SUDO-Manager
  issues: https://github.com/josephoaks/Cockpit-SUDO-Manager/issues
  license: Apache-2.0
  description: |
    Manage sudo policy on Linux systems in a structured, auditable, and
    policy-driven way. Developed for SUSE Linux.
